import { readFileSync } from "fs"
import { join } from "path";

export const loaderCode = () => readFileSync(join(__dirname, '../../loader.min.js'), 'utf-8');

export const defaultAllowGlobals = [
  'crypto',
  'console',
  'customElements',
  'devicePixelRatio',
  'fullscreen',
  'history',
  'indexedDB',
  'innerHeight',
  'innerWidth',
  'location',
  'localStorage',
  'name',
  'navigator',
  'origin',
  'outerHeight',
  'outerWidth',
  'pageXOffset',
  'pageYOffset',
  'screen',
  'screenX',
  'screenY',
  'screenLeft',
  'screenTop',
  'sessionStorage',
  'scrollbars',
  'scrollX',
  'scrollY',
  'atob',
  'alert',
  'btoa',
  'cancelAnimationFrame',
  'cancelIdleCallback',
  'fetch',
  'requestAnimationFrame',
  'setTimeout',
  'setInterval',
  'clearTimeout',
  'clearInterval',
  'confirm',
  'createImageBitmap',
  'focus',
  'getComputedStyle',
  'getSelection',
  'open',
  'postMessage',
  'prompt',
  'requestIdleCallback',
  'scroll',
  'scrollBy',
  'scrollTo',
  'stop',
  'addEventListener',
  'removeEventListener',
]